import type { Metadata } from 'next';
import './globals.css';
import { Sidebar } from '@/components/organisms/Sidebar/Sidebar';
import { Header } from '@/components/organisms/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex antialiased`}>
        <Sidebar />
        <div className="flex-1 flex flex-col overflow-auto">
          <Header />

          <main className="flex-1 p-6">{children}</main>
        </div>
        {children}
      </body>
    </html>
  );
}
