"""Add tenant_id to projects

Revision ID: 8d354f450edb
Revises: 
Create Date: 2025-12-10 22:18:34.770333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d354f450edb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('tenant_id', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('responsible_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    op.add_column('tasks', sa.Column('responsible_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'responsible_id')
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_column('projects', 'responsible_id')
    op.drop_column('projects', 'tenant_id')
    # ### end Alembic commands ###
